### ISSUE TITLE
`get_token` returns `&Vec<u8>`

### ISSUE THREAD

**Issue by ShadowJonathan** [martindisch/coap-lite#17]
Something i noticed while looking at the documentation, I think the general ergonomic usage of returning byte slices is returning `&[u8]` over `&Vec<u8>`

**Comment by martindisch** [comment]
You're absolutely right, that would be the idomatic way to do it. I could update right away and publish a new version, but since it's a breaking change I'd rather wait in case you discover more things.
So I created a branch and a PR to stage changes for the next version at https://github.com/martindisch/coap-lite/pull/18. If it helps you can base your work on that branch, I'll merge that at some point in the future.

**Comment by martindisch** [comment]
I'm about to release a new major version, so this is included.
